name: guide
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=11.8
  - pip:
    - ninja==1.11.1
    - lpips==0.1.4
    - click==8.1.7
    - timm==1.0.7
    - yacs==0.1.8
    - opencv-python==4.10.0